services:
  jekyll:
    image: jvconseil/jekyll-docker
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll:Z
      - bundle-cache:/usr/local/bundle
    command: "jekyll serve --config _config.yml,_config-dev.yml"

volumes:
  bundle-cache:
